language: python
python:
  - "3.8"
stages:
  - name: deploy
jobs:
  - stage: deploy
    name: Heroku Deploy
    script: /bin/true
    deploy:
      provider: heroku
      app: ymu-codenation-projetofinal
      on: master
      run: "python manage.py migrate"