language: python
python:
  - "3.8"
stages:
  - name: deploy
jobs:
  include:
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        app: ymu-codenation-projetofinal
        api_key:
          secure: HEROKU_API_KEY
        on: master
        run: "python manage.py migrate"