# Generated by Django 3.0.8 on 2020-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erro',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erro',
            name='event',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erro',
            name='level',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('debug', 'debug'), ('error', 'error'), ('warning', 'warning'), ('information', 'information')], max_length=15),
        ),
        migrations.AddField(
            model_name='erro',
            name='origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='erro',
            name='producao',
            field=models.CharField(blank=True, choices=[('Homologacao', 'Homologacao'), ('Dev', 'Dev')], max_length=15),
        ),
        migrations.AlterField(
            model_name='erro',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
