# Generated by Django 3.0.8 on 2020-07-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20200715_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erro',
            name='producao',
        ),
        migrations.AddField(
            model_name='erro',
            name='ambiente',
            field=models.CharField(blank=True, choices=[('Homologacao', 'Homologacao'), ('Dev', 'Dev'), ('Produção', 'Produção')], max_length=15, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='erro',
            name='origem',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
