# Generated by Django 3.0.8 on 2020-07-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20200715_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Erro',
            new_name='Log',
        ),
    ]
