# Generated by Django 3.0.8 on 2020-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20200715_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
    ]
